Feature/machine learning/gcp connection for clip
GreenTeaProgrammers/WhereChildBus pull request #54
Opened 2024-02-13 11:02 UTC by lovelovetrb

## チケットへのリンク

- https://github.com/GreenTeaProgrammers/WhereChildBus/issues/52

## やったこと

- GCS上に格納されている画像ファイルを取得する処理の実装
- 切り出した画像をGCS上に保存する処理の実装
- GCSから取得する処理とローカル環境の画像を利用する処理の両立

## やらないこと

- GCP Cloud Functionへの対応

## できるようになること（ユーザ目線）

- なし

## できなくなること（ユーザ目線）

- なし

## 動作確認

- [] ローカル環境において，GCSとローカルそれぞれに保存されている画像を取得し保存まで行われることを確認

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
detectFaceAndClip.pyの記述が冗長すぎる気がしているので良い書き方あればガッツリめにレビューしてもらえると幸いです

2024-02-13 13:48 UTC, KinjiKawaguchi requested changes
レビューは一旦ここまでです。
Secretディレクトリを作成したら、git ignoreとenvファイルの更新をお忘れなく。

2024-02-13 13:48 UTC, KinjiKawaguchi commented on machine_learning/.gitignore
> +service_account_where_child_bus.json
Secrets系のものはSecretsディレクトリなどを作ってまとめるのが一般的です。

2024-02-13 13:48 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/data/detectFaceAndClip.py
> +    return images
ローカルとリモートの処理を分けていますが、共通の処理が多いため、関数をさらに細かく分割することで可読性と再利用性を上げましょう

2024-02-13 13:48 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/data/detectFaceAndClip.py
> +    return images
```suggestion
def load_image(args, blobs=None):
    """画像の読み込みを行うラッパー関数"""
    if args.env == "local":
        return load_image_from_local(args.img_dir_path)
    elif args.env == "remote":
        return load_image_from_remote(blobs)
```

2024-02-13 13:48 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/data/detectFaceAndClip.py
> +            image = cv2.imread(args.image_dir_path + image_path)
```suggestion
            image = cv2.imread(os.path.join(args.img_dir_path, image_path))
```
実際にコマンドライン引数で受け取るオプションと絶妙に変数名が違うのは保守性に欠ける気がします

2024-02-13 13:48 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/data/detectFaceUtil.py
> +    resized_face = cv2.resize(face_roi, image_size, interpolation=cv2.INTER_AREA)
cv2.INTER_LINEARやcv2.INTER_CUBICなどは使わないですか
特に拡大の時とか

2024-02-13 16:09 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/detectFaceUtil.py
> +    resized_face = cv2.resize(face_roi, image_size, interpolation=cv2.INTER_AREA)
調べてみたところ今回のユースケースに近そうなのがINTER_CUBICでしたね
interpolationで指定できるすべてのパターンを試して主観評価してみましたがINTER_CUBICが一番良さそうなのでこれにしたいと思います！！

2024-02-13 16:13 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/detectFaceAndClip.py
> +            image = cv2.imread(args.image_dir_path + image_path)
タイポでした😭

2024-02-14 08:58 UTC, KinjiKawaguchi requested changes

2024-02-14 08:58 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +        return load_image_fromm_local(args.img_dir_path)
```suggestion
        return load_image_from_local(args.img_dir_path)
```

2024-02-14 08:58 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +def load_image_fromm_local(img_dir_path):
```suggestion
def load_image_from_local(img_dir_path):
```

2024-02-14 08:58 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +    for image_path in os.listdir(img_dir_path):
メモリに留意

2024-02-14 08:58 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +        for file in os.listdir(save_dir_path):
メモリに留意

2024-02-14 08:58 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +    logger.info("Done")
```suggestion
def main(args):
    logger.info(f"Environment: {args.env}")

    if args.env == "local":
        images = load_image(args)
        save_faces_locally(images, args.save_dir_path)
    elif args.env == "remote":
        client = initialize_gcs_client()
        if client:
            bucket = client.bucket(os.environ.get("BUCKET_NAME"))
            images = load_images_from_gcs(client, args.nursery_id, args.child_id)
            save_faces_to_gcs(images, args.nursery_id, args.child_id, bucket)
    else:
        logger.error(f"Unknown environment: {args.env}")

    logger.info("Processing complete.")
    
```


mainをもう少し分割しましょう

2024-02-14 15:33 UTC, KinjiKawaguchi requested changes

2024-02-14 15:33 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +    logger.info("Done")
```suggestion
def main(args):
    # ログ出力
    logger.info(f"環境: {args.env}")

    # 設定ファイル読み込み
    with open("src/face_detect_model/config.yaml", "r") as f:
        config = yaml.safe_load(f)

    # 顔検出処理
    detect_face(args, config)

    # 終了メッセージ
    logger.info("処理完了")
```

2024-02-14 15:33 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +    logger.info("Done")
main関数が責務を負いすぎです。
↑ぐらいのわかりやすさにしましょう。

2024-02-16 11:10 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/DetectFaceAndClip/detectFaceAndClip.py
> +    logger.info("Done")
細分化してみました．
よりできそうですが，どうなんでしょうか．

2024-02-16 12:36 UTC, merged