Feature/machine learning/augmentation
GreenTeaProgrammers/WhereChildBus pull request #71
Opened 2024-02-14 05:37 UTC by Hosi121

## チケットへのリンク

- https://github.com/orgs/GreenTeaProgrammers/projects/hogehoge-fugafugaaa

## やったこと

- augmatation用のコードを実装

## やらないこと

- なし

## できるようになること（ユーザ目線）

- なし

## できなくなること（ユーザ目線）

- なし

## 動作確認

## その他

2024-02-14 07:22 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +        return [(label, augmented_image) for augmented_image in augmented_images]
拡張をデータ取得時点で行ってるんですが，これを__init__が呼ばれた時点でデータ拡張を行って，__getitem__が呼ばれた時returnされるデータは画像とラベル1組にしたいです！

2024-02-14 07:26 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +
ここでもうtransformさせた複数の拡張データを展開してface_dataにappendする形でいいかな〜と思います．

2024-02-14 07:30 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +            augmented_images.append(augmented_image)
ランダム変換が水平変換のみなので，おそらく5回の中で最低2枚は同じような画像が出力されてしまうような気がするのですがどうでしょう...
5回loopするなら5回すべて違うデータが出力されて欲しさはあるのですが...

2024-02-14 07:32 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +            augmented_images.append(augmented_image)
例えばdefault_transformsが引数を受け取って，RandomHorizontalFlipのところに引数的に変換処理を受け取り，与えられる引数がforループ内でランダムに変わるとかですかね

2024-02-14 07:37 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +    def augment_image(self, image, num_variations=5):
デフォルトの画像も学習データとして保持させたいんですが，どこかに組み込めますか？
__init__内でこの関数を呼び出す時でもいいし，augment_imageの返り値に元の画像データが残っててもいいと思われます！

2024-02-14 07:37 UTC, lovelovetrb requested changes
こんな感じでどうでしょう

2024-02-15 14:27 UTC, lovelovetrb requested changes
お疲れ様です！

2024-02-15 14:27 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +    # ランダムな変換を適用するための拡張設定を強化
この処理をメソッド化するのはどうでしょうか？

2024-02-15 14:27 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
>          ])
下部にあるtransforms.Composeの処理と置き換わるかと思います

2024-02-15 14:27 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +                                    transforms.RandomCrop((224, 224))], p=0.5),
RandomにRandomがかかっている？

```
transforms.RandomApply(transforms.Resize(256, 256), p=0.5),
transforms.RandomCrop((224, 224))], p=0.5))
```

2024-02-15 14:27 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
> +            transforms.RandomApply([transforms.RandomRotation(degrees=15)], p=0.5),
180にすれば360度ランダムで回転しそう？

https://pytorch.org/vision/main/generated/torchvision.transforms.RandomRotation.html

2024-02-15 14:27 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/data/faceDetectDataset.py
>          ])
__init__で元画像を保持するためにつかっていそうだったので残してもいいかも，
ただ，Resizeする必要はないかも？(もともとclopされているため

2024-02-17 11:29 UTC, lovelovetrb approved these changes
![LGTM](https://images.lgtmgen.org/fb52fc32-d770-407e-ab40-0d5e440eff53)

2024-02-17 11:32 UTC, lovelovetrb approved these changes

2024-02-17 11:33 UTC, KinjiKawaguchi approved these changes

2024-02-17 11:33 UTC, merged