refactor(ml): 顔検出とクリッピングに関するコードのリファクタリング
GreenTeaProgrammers/WhereChildBus pull request #92
Opened 2024-02-16 16:12 UTC by lovelovetrb

## チケットへのリンク

- なし

## やったこと

- 顔検出とクリッピングに関するコードのリファクタリング
　- detectFaceUtil.pyのimportをプロジェクトの直下からのimportに変更
　- 一部logをf-stringに変更
　- 一部エラーハンドリングを追加

## やらないこと

- なし

## できるようになること（ユーザ目線）

- なし

## できなくなること（ユーザ目線）

- なし

## 動作確認

- [] 別途，gRPC server用のコードでsrcディレクトリからの実行ができることを確認しました

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2024-02-16 17:12 UTC, KinjiKawaguchi requested changes

2024-02-16 17:12 UTC, KinjiKawaguchi commented on machine_learning/src/face_detect_model/DetectFaceAndClip/__init.py
__init.pyになってしまってます。

2024-02-17 04:42 UTC, lovelovetrb commented on machine_learning/src/face_detect_model/DetectFaceAndClip/__init.py
ほんとだ

2024-02-17 06:01 UTC, KinjiKawaguchi approved these changes

2024-02-17 06:02 UTC, merged